name: Build and Deploy Zola Site
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: docker
    container:
      image: docker:27.1-dind
    steps:
      - uses: actions/checkout@v4
      - run: docker compose build zola
      - run: docker compose up -d zola
