name: Build and Deploy Zola Site
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and run Zola site
        run: |
          docker compose build zola
          docker compose up -d zola
